// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Premium   bool      `json:"premium"`
	Status    bool      `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
